version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "humus"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ryuhd52g2dyw"
s3_prefix = "humus"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
